services:
  e-api:
    build: .
    ports:
      - "5051:5051"
    depends_on:
      - redis
    environment:
      - IS_DOCKER=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOST=${DB_HOST}  # Dynamic host for local vs. Fly.io
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    volumes:
      - .:/app
      - /app/node_modules  # Prevents overwriting node_modules
    develop:
      watch:
        - action: sync
          path: .  # Watch everything inside the project
          target: /app
          ignore:
            - node_modules/
            - .git/
    command: npm run dev  # Start with nodemon in development

  redis:
    image: redis:7-alpine
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  redis_data:
